export const Panes = [
  {
    paneName: "Pane 1",
    isActive: true,
    isHovered: false,
    isPlaying: false,
    isVideoPane: false,
  },
  {
    paneName: "Pane 2",
    isActive: false,
    isHovered: true,
    isPlaying: false,
    isVideoPane: false,
  },
  {
    paneName: "Pane 3",
    isActive: false,
    isHovered: false,
    isPlaying: false,
    isVideoPane: false,
  },
  {
    paneName: "Pane 4",
    isActive: true,
    isHovered: false,
    isPlaying: false,
    isVideoPane: false,
  },
  {
    paneName: "Pane 5",
    isActive: false,
    isHovered: true,
    isPlaying: false,
    isVideoPane: false,
  },
  {
    paneName: "Pane 6",
    isActive: true,
    isHovered: false,
    isPlaying: false,
    isVideoPane: false,
  },
  {
    paneName: "Pane 7",
    isActive: false,
    isHovered: true,
    isPlaying: false,
    isVideoPane: false,
  },
  {
    paneName: "Pane 8",
    isActive: false,
    isHovered: false,
    isPlaying: false,
    isVideoPane: false,
  },
  {
    paneName: "Pane 9",
    isActive: true,
    isHovered: false,
    isPlaying: false,
    isVideoPane: false,
  },
  {
    paneName: "Pane 10",
    isActive: false,
    isHovered: true,
    isPlaying: false,
    isVideoPane: false,
  },
  {
    paneName: "Pane 11",
    isActive: true,
    isHovered: false,
    isPlaying: false,
    isVideoPane: false,
  },
  {
    paneName: "Pane 12",
    isActive: false,
    isHovered: true,
    isPlaying: false,
    isVideoPane: true,
  },
  {
    paneName: "Pane 13",
    isActive: false,
    isHovered: false,
    isPlaying: false,
    isVideoPane: true,
  },
  {
    paneName: "Pane 14",
    isActive: true,
    isHovered: false,
    isPlaying: false,
    isVideoPane: true,
  },
  {
    paneName: "Pane 15",
    isActive: false,
    isHovered: true,
    isPlaying: false,
    isVideoPane: true,
  },
];
