export const Panes = [
  {
    paneName: "Enigmatic Echoes",
    isActive: true,
    isHovered: false,
    isPlaying: false,
    isVideoPane: false,
  },
  {
    paneName: "Chromatic Cascade",
    isActive: false,
    isHovered: true,
    isPlaying: false,
    isVideoPane: false,
  },
  {
    paneName: "Ethereal Embrace",
    isActive: false,
    isHovered: false,
    isPlaying: false,
    isVideoPane: false,
  },
  {
    paneName: "Whispering Whirlpool",
    isActive: true,
    isHovered: false,
    isPlaying: false,
    isVideoPane: false,
  },
  {
    paneName: "Radiant Rhapsody",
    isActive: false,
    isHovered: true,
    isPlaying: false,
    isVideoPane: false,
  },
  {
    paneName: "Spectral Serenity",
    isActive: true,
    isHovered: false,
    isPlaying: false,
    isVideoPane: false,
  },
  {
    paneName: "Luminescent Labyrinth",
    isActive: false,
    isHovered: true,
    isPlaying: false,
    isVideoPane: false,
  },
  {
    paneName: "Celestial Symphony",
    isActive: false,
    isHovered: false,
    isPlaying: false,
    isVideoPane: false,
  },
  {
    paneName: "Harmonic Hues",
    isActive: true,
    isHovered: false,
    isPlaying: false,
    isVideoPane: false,
  },
  {
    paneName: "Mystic Melody",
    isActive: false,
    isHovered: true,
    isPlaying: false,
    isVideoPane: false,
  },
  {
    paneName: "Vibrant Voyage",
    isActive: true,
    isHovered: false,
    isPlaying: false,
    isVideoPane: false,
  },
  {
    paneName: "Infinite Illusion",
    isActive: false,
    isHovered: true,
    isPlaying: false,
    isVideoPane: true,
  },
  {
    paneName: "Cosmic Canvas",
    isActive: false,
    isHovered: false,
    isPlaying: false,
    isVideoPane: true,
  },
  {
    paneName: "Aurora Allegro",
    isActive: true,
    isHovered: false,
    isPlaying: false,
    isVideoPane: true,
  },
  {
    paneName: "Tranquil Tapestry",
    isActive: false,
    isHovered: true,
    isPlaying: false,
    isVideoPane: true,
  },
];
